import 'package:flutter/material.dart';
import 'package:dva232_project/routes.dart';
import 'package:dva232_project/screens/tests/shared.dart';
import 'package:dva232_project/widgets/back_icon_button.dart';
import 'package:dva232_project/widgets/back_nav_button.dart';
import 'package:dva232_project/widgets/nav_button.dart';
import 'package:flutter/material.dart';
import 'package:dva232_project/widgets/languide_navbar.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:dva232_project/screens/results/reading.dart';

class WritingQuestion extends StatefulWidget {
  @override
  _WritingQuestionState createState() => _WritingQuestionState();
}

class _WritingQuestionState extends State<WritingQuestion> {
  String option1 = '          1          ';
  String option2 = '          2          ';
  String option3 = '          3          ';
  String option4 = '          4          ';
  String option5 = '          5          ';

  String oneA = 'Secondly';
  String oneB = 'Second';
  String oneC = 'Previously';
  String twoA = 'It should be noted';
  String twoB = 'Obviously';
  String twoC = 'Finally';
  String threeA = 'absolutely';
  String threeB = 'first and foremost';
  String threeC = 'however';
  String fourA = 'Unlike';
  String fourB = 'Despite';
  String fourC = 'In particular';
  String fiveA = 'besides';
  String fiveB = 'therefore';
  String fiveC = 'whereas';

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.purple,
          centerTitle: true,
          title: Text(
            'Test',
            style: TextStyle(
                fontWeight: FontWeight.normal,
                color: Colors.white,
                fontSize: 20),
          ),
        ),
        body: Container(
          padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          child: SingleChildScrollView(
            child: Column(
              children: [
                RichText(
                  text: TextSpan(
                      text: '',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 17,
                      ),
                      children: [
                        TextSpan(
                          text:
                              '''His paper integrates elements from the theory of agency, the theory of property rights and the theory of finance to develop a theory of the ownership structure of the firm. Firstly, we define the concept of agency costs and show its relationship to the ‘separation and control’ issue. ''',
                        ),
                        TextSpan(
                            text: option1,
                            style: TextStyle(
                                color: Colors.purple,
                                fontWeight: FontWeight.bold,
                                decoration: TextDecoration.underline,
                                decorationThickness: 2)),
                        TextSpan(
                            text:
                                ''', we investigate the nature of the agency costs generated by the existence of debt and outside equity, demonstrate who bears these costs and why, and investigate the Pareto optimality of their existence. \n'''),
                        TextSpan(
                            text: option2,
                            style: TextStyle(
                                color: Colors.purple,
                                fontWeight: FontWeight.bold,
                                decoration: TextDecoration.underline,
                                decorationThickness: 2)),
                        TextSpan(
                            text:
                                ''', we provide a new definition of the firm, and show how our analysis of the factors influencing the creation and issuance of debt and equity claims is a special case of the supply side of the completeness of markets problem.The directors of such companies, '''),
                        TextSpan(
                            text: option3,
                            style: TextStyle(
                                color: Colors.purple,
                                fontWeight: FontWeight.bold,
                                decoration: TextDecoration.underline,
                                decorationThickness: 2)),
                        TextSpan(
                            text:
                                ''', being the managers rather of other people's money than of their own, it cannot well be expected, that they should watch over it with the same anxious vigilance with which the partners in a private copartnery frequently watch over their own. \n'''),
                        TextSpan(
                            text: option4,
                            style: TextStyle(
                                color: Colors.purple,
                                fontWeight: FontWeight.bold,
                                decoration: TextDecoration.underline,
                                decorationThickness: 2)),
                        TextSpan(
                            text:
                                ''' the stewards of a rich man, they are not apt to consider attention to small matters as not for their master's honour, and very easily give themselves a dispensation from having it. Negligence and profusion, '''),
                        TextSpan(
                            text: option5,
                            style: TextStyle(
                                color: Colors.purple,
                                fontWeight: FontWeight.bold,
                                decoration: TextDecoration.underline,
                                decorationThickness: 2)),
                        TextSpan(
                            text:
                                ''', must always prevail, more or less, in the management of the affairs of such a company.'''),
                      ]),
                ),
                SizedBox(height: 32),
                Column(
                  children: [
                    Text(
                      'Number 1',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        color: Colors.purple,
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option1 = oneA;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option1 == oneA
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'a) $oneA',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option1 == oneA ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option1 = oneB;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option1 == oneB
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'b) $oneB',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option1 == oneB ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option1 = oneC;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option1 == oneC
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'c) $oneC',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option1 == oneC ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                SizedBox(height: 32),
                Column(
                  children: [
                    Text(
                      'Number 2',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        color: Colors.purple,
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option2 = twoA;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option2 == twoA
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'a) $twoA',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option2 == twoA ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option2 = twoB;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option2 == twoB
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'b) $twoB',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option2 == twoB ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option2 = twoC;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option2 == twoC
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'c) $twoC',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option2 == twoC ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                SizedBox(height: 32),
                Column(
                  children: [
                    Text(
                      'Number 3',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        color: Colors.purple,
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option3 = threeA;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option3 == threeA
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'a) $threeA',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color: option3 == threeA
                                ? Colors.white
                                : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option3 = threeB;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option3 == threeB
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'b) $threeB',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color: option3 == threeB
                                ? Colors.white
                                : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option3 = threeC;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option3 == threeC
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'c) $threeC',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color: option3 == threeC
                                ? Colors.white
                                : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                SizedBox(height: 32),
                Column(
                  children: [
                    Text(
                      'Number 4',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        color: Colors.purple,
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option4 = fourA;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option4 == fourA
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'a) $fourA',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option4 == fourA ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option4 = fourB;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option4 == fourB
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'b) $fourB',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option4 == fourB ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option4 = fourC;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option4 == fourC
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'c) $fourC',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option4 == fourC ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                SizedBox(height: 32),
                Column(
                  children: [
                    Text(
                      'Number 5',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        color: Colors.purple,
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option5 = fiveA;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option5 == fiveA
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'a) $fiveA',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option5 == fiveA ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option5 = fiveB;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option5 == fiveB
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'b) $fiveB',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option5 == fiveB ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 8,
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          option5 = fiveC;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        padding:
                            EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        decoration: BoxDecoration(
                            color: option5 == fiveC
                                ? Colors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            border:
                                Border.all(color: Colors.purple, width: 1.5)),
                        child: Text(
                          'c) $fiveC',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w400,
                            color:
                                option5 == fiveC ? Colors.white : Colors.purple,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                SizedBox(height: 32),
                GestureDetector(
                  onTap: () {Navigator.pushNamed(context, Routes.writingResults, arguments: null);},
                  child: Container(
                    width: double.infinity,
                    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                    decoration: BoxDecoration(
                        color: Colors.purple,
                        borderRadius: BorderRadius.all(Radius.circular(8)),
                        border: Border.all(color: Colors.purple, width: 1.5)),
                    child: Text(
                      'Submit Answers',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.w700,
                          color: Colors.white),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
